language: node_js

node_js:
  - node

services:
  - docker

env:
  - DOCKER_COMPOSE_VERSION=3.3

addons:
  apt:
    packages:
      - docker-ce

before_install:
  - docker-compose -f docker-compose.test.yml up
